---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: dev24cr.azurecr.io/web:latest
        env:
        - name: NAME
          value: "My Demo Application"
        - name: Dbstring
          value: {{.Values.dbstring}}
        ports:
        - containerPort: 80